version: '2'

services:
  node-expel:
    depends_on:
      - zookeeper
      - kafka
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - 'ARTIFACTORY_PW=${ARTIFACTORY_PW}'
      - 'PROJECT_NAME=${CIRCLE_PROJECT_REPONAME}'
      - 'KAFKA_HOSTS=kafka:9092'
      - 'CI=true'
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: 'test_topic:1:1'
