version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.0

workflows:
  build:
    jobs:
      - aws-ecr/build_and_push_image:
          repo: my-repo-staging
      - aws-ecr/build_and_push_image:
          repo: my-repo-prod
  
